### PR TITLE
[IMPORTANT] Discontinuation of intel-vaapi-driver Project

### PR DESCRIPTION
**Pull request by xhaihao**

### CODE REVIEW

**Review by uartie — APPROVED** [review]

**Comment by ceyusa** [comment]
Have you thought about [archiving](https://docs.github.com/en/repositories/archiving-a-github-repository/archiving-repositories) the project?

Nonetheless, also, it would be great if someone in the community steps up as maintainer, that you somehow might acknowledge; otherwise I suspect we'll see a problematic fragmentation of the project.

**Comment by xhaihao** [comment]
> Have you thought about [archiving](https://docs.github.com/en/repositories/archiving-a-github-repository/archiving-repositories) the project?
> 
Thanks for the suggestion, I'll archive this repo.

**Comment by mlawson27** [comment]
Any chance of a final 2.4.2/2.5 release before archival?  Doesn't look like a ton has changed since 2.4.1, so probably not a big deal, but it'd be kind of nice to have an official tag with those commits included.

**Comment by satmandu** [comment]
> Any chance of a final 2.4.2/2.5 release before archival?  Doesn't look like a ton has changed since 2.4.1, so probably not a big deal, but it'd be kind of nice to have an official tag with those commits included.

Especially for those who are still using Skylake or older hardware...

**Pull request merged**
