### PR TITLE
Return surface width/height in pixels

### PR DESCRIPTION
**Pull request by xhaihao**
width/height in VADRMPRIMESurfaceDescriptor specifies the
surface width/height in pixels in VA-API, so we should set
the corresponding variables in pixels in the driver

This fixes https://github.com/01org/intel-vaapi-driver/issues/342,
thanks pkerling for the investigation and proposed fix for this issue.

Signed-off-by: Xiang, Haihao <haihao.xiang@intel.com>

### CODE REVIEW

**Comment by fhvwy** [comment]
I'm not sure that these numbers are the right ones to use.  The surface is likely to be larger than `orig_width` by `orig_height` because of alignment rounding, which can be relevant when someone wanting to render to a surface works in units larger than individual pixels.  For example, the H.264 decoder needs to know that there is space for whole macroblocks around the edges - an external renderer may have a similar requirement, and therefore should be told the size of the whole surface so that they can deal with these cases properly.

I think that therefore wants `obj_surface->width / bpp_1stplane_by_fourcc(fourcc)` and `obj_surface->height`, though I haven't checked that that is right in all cases.

**Comment by xhaihao** [comment]
if a larger surface is needed for a codec, the application should specify the larger size when creating a surface.  E.g. a 1920x1088 surface is created in mpv for 1080x1080 video decoding. 

On the other hand, obj_surface->width is the stride (or pitch) of the surface, so it should follow the alignment, e.g. for a tiled surface. so obj_surface->width / bpp_1stplane_by_fourcc(fourcc) is not what you want in this case.

**Comment by fhvwy** [comment]
Hmm, right - adjustment for alignment is applied after the multiplication by element size so the simple division isn't helpful.

I guess I'm unclear what the intent of these fields is - having written code using the feature I have never used them.  You have to track the size of the image on the surface separately and will use that for things like EGL import, so I'm not really seeing any use-case here.  Given that, I suppose having the size as passed to vaCreateSurfaces() is as good as any other similar value we might offer.  Still, the one user example we have here demonstrated that their presence invites people to use it incorrectly - should something be done about that?

**Comment by xhaihao** [comment]
@fhvwy Sorry, what's the example you mentioned in the above comment?

**Comment by fhvwy** [comment]
@xhaihao  I mean the original report which prompted this (#342), which is the one example I have of someone who isn't me using this API.

**Pull request merged**
