### PR TITLE
Add test for config creation with packed headers

### PR DESCRIPTION
**Pull request by fhvwy**
Iterates across all profiles and entrypoints creating configs, ensuring
that all valid combinations of packed headers and accepted and all
invalid combinations are rejected.

@uartie  I don't really have any idea what I am doing in this test framework.  There appears to be a lot of magic to do clever stuff, but I can't make sense of it so I just have a single function which loops over everything doing the required checks directly.  If you'd like to take this and turn it into something more conforming to how you think the framework should be used then please do.

### CODE REVIEW

**Comment by uartie** [comment]
Yeh, there's a lot of changes that could be made here.  I'll try to take a stab at it next week if I have time.

**Comment by uartie** [comment]
You can remove the patch here that is already part of the other PR.

**Comment by fhvwy** [comment]
> You can remove the patch here that is already part of the other PR.

Sure, done.  (The test of course fails a large number of cases without the other patch.)

**Comment by uartie** [comment]
understood... thanks.

**Comment by uartie** [comment]
Superseded by intel/libva-utils#105

**Pull request closed without merging**
